import type { OS, QuestionnaireResponses } from "./types";

export interface StepTemplate {
  id: string;
  section: string;
  title: string;
  description: string;
  why: string;
  click_steps: string[];
  notes: string[];
  links: { label: string; url: string }[];
  target_urls: string[];
  completion_criteria: string;
  showIf?: (r: QuestionnaireResponses) => boolean;
  codeContent?: Partial<Record<OS, string>>;
}

export const STEP_TEMPLATES: StepTemplate[] = [
  // ── Core Infrastructure ───────────────────────────────────────────────
  {
    id: "claude-max",
    section: "infrastructure",
    title: "Confirm Your Claude Max Plan",
    description: "Claude Code — the engine behind everything in this guide — requires a Claude Max subscription. Confirm you have an active Max plan before continuing.",
    why: "Claude Code is what turns Claude from a chatbot into a personal assistant that takes actions. Max includes it at no extra cost.",
    click_steps: [
      "Go to claude.ai and sign in.",
      "Click your profile icon (top right) → Billing.",
      "Confirm you're on the Max plan ($100/mo). If not, upgrade before continuing.",
    ],
    notes: ["No API key or separate developer account needed — Max covers all usage in this guide."],
    links: [{ label: "claude.ai/billing", url: "https://claude.ai/settings/billing" }],
    target_urls: ["claude.ai", "claude.ai/settings/billing"],
    completion_criteria: "Active Claude Max subscription confirmed",
  },
  {
    id: "node",
    section: "infrastructure",
    title: "Install Node.js",
    description: "Node.js is required to install Claude Code and most MCP connectors.",
    why: "Most integrations in this guide are npm packages. Node.js is the runtime that lets them run on your machine.",
    click_steps: [
      "Go to nodejs.org and click the LTS download button.",
      "Run the installer and accept all defaults.",
      "Restart your computer after the install finishes.",
    ],
    notes: ["Download the LTS version (left button) — it's the stable release."],
    links: [{ label: "Download Node.js LTS", url: "https://nodejs.org" }],
    target_urls: ["nodejs.org"],
    completion_criteria: "Node.js installed and `node --version` runs in terminal",
  },
  {
    id: "python",
    section: "infrastructure",
    title: "Install Python",
    description: "Python is required for the Windows MCP server and the Personal Knowledge Base server.",
    why: "Two components run on Python: the Windows MCP server (lets Claude interact with your OS) and the PKB memory server.",
    click_steps: [
      "Go to python.org/downloads and click the yellow Download button.",
      "Run the installer.",
      "⚠️ On the first screen, check 'Add Python to PATH' before clicking Install Now.",
      "Click Install Now and wait for it to finish.",
    ],
    notes: ["The PATH checkbox is near the bottom of the first installer screen and is unchecked by default — missing it causes problems."],
    links: [{ label: "Download Python", url: "https://www.python.org/downloads/" }],
    target_urls: ["python.org", "python.org/downloads"],
    completion_criteria: "Python installed with PATH configured; `python --version` runs in terminal",
    showIf: r => r.os === "windows" || r.pkb || r.supabase_db,
  },
  {
    id: "claude-desktop",
    section: "infrastructure",
    title: "Install Claude Desktop",
    description: "Claude Desktop is the application that hosts all your MCP connectors. It's the control panel for your entire setup.",
    why: "When you add a connector (Calendar, Gmail, GitHub, etc.), it gets saved in a config file that Claude Desktop manages. Claude Code reads that same file — so configuring Desktop once gives you those connections everywhere.",
    click_steps: [
      "Go to claude.ai/download and click the download button for your operating system.",
      "Run the installer and follow the prompts.",
      "Open Claude Desktop and sign in with your Claude.ai account.",
    ],
    notes: ["You'll come back to Claude Desktop's Settings → Connectors throughout this guide to add MCP servers."],
    links: [{ label: "Download Claude Desktop", url: "https://claude.ai/download" }],
    target_urls: ["claude.ai/download"],
    completion_criteria: "Claude Desktop installed and signed in",
  },
  {
    id: "claude-code",
    section: "infrastructure",
    title: "Install Claude Code",
    description: "Claude Code is Anthropic's command-line tool — it enables automations, Telegram, scheduled tasks, and everything that runs in the background.",
    why: "Claude Desktop handles the GUI and MCP connections. Claude Code is what enables everything that runs without you — receiving messages, executing scheduled tasks, running as a persistent background session.",
    click_steps: [
      "Open a terminal. On Windows: press Win+X and choose 'Terminal' or 'Windows PowerShell'. On Mac: press Cmd+Space, type Terminal, and press Enter.",
      "You don't need to be in any specific folder — this command installs Claude Code system-wide, so location doesn't matter.",
      "Copy the install command shown in the box below, paste it into the terminal, and press Enter. It downloads and installs Claude Code and may take 1-2 minutes.",
      "When it finishes, type `claude` and press Enter. A prompt will ask you to sign in — choose 'Sign in with Claude.ai'.",
      "After signing in, type `hello` and press Enter. If Claude responds in the terminal, installation is complete.",
    ],
    notes: [
      "The install command is: npm install -g @anthropic/claude-code",
      "Mac users: if you see 'permission denied', run `sudo npm install -g @anthropic/claude-code` instead and enter your computer password when prompted.",
      "Wait for the cursor/prompt to return before typing `claude` — the install is still running while the terminal is busy.",
    ],
    links: [],
    target_urls: [],
    completion_criteria: "Claude Code installed; `claude --version` runs and user is authenticated",
    codeContent: {
      windows: "npm install -g @anthropic/claude-code",
      mac: "npm install -g @anthropic/claude-code",
    },
  },
  // ── Google ────────────────────────────────────────────────────────────
  {
    id: "google-oauth",
    section: "google",
    title: "Set Up Google OAuth",
    description: "Create a Google Cloud OAuth app so Claude can access your Google account. This is a one-time setup in Google Cloud Console.",
    why: "The Google MCP connectors need OAuth credentials to access your Gmail, Calendar, or Drive on your behalf. You create these credentials once and they work for all Google services you enable.",
    click_steps: [
      "Go to console.cloud.google.com and sign in with your Google account.",
      "Create a new project (or select an existing one) — name it something like 'Claude MCP'.",
      "In the sidebar, go to APIs & Services → OAuth consent screen.",
      "Select 'External' user type and fill in the app name ('Claude') and your email. Save.",
      "Go to APIs & Services → Credentials → Create Credentials → OAuth client ID.",
      "Choose 'Desktop app' as the application type. Name it and click Create.",
      "Download the JSON file — you'll need it in the next step.",
    ],
    notes: [
      "You only need to do this once, even if you have multiple Google accounts.",
      "Enable the specific APIs you need: Google Calendar API, Gmail API, Google Drive API.",
    ],
    links: [{ label: "Google Cloud Console", url: "https://console.cloud.google.com" }],
    target_urls: ["console.cloud.google.com"],
    completion_criteria: "OAuth client credentials JSON downloaded",
    showIf: r => r.google_gmail || r.google_calendar || r.google_drive,
  },
  {
    id: "google-mcp",
    section: "google",
    title: "Install the Google MCP Connector",
    description: "Add the Google MCP server to Claude Desktop so Claude can read your Gmail, Calendar, and Drive.",
    why: "The Google MCP connector is what lets Claude actually read your email, check your calendar, and find files — without you having to copy-paste anything.",
    click_steps: [
      "Open Claude Desktop → Settings → Connectors.",
      "Search for 'Google' in the connector library.",
      "Click Install and follow the OAuth flow to connect your account(s).",
      "If you have multiple accounts, add each one separately.",
    ],
    notes: ["Each Google account needs its own connector entry."],
    links: [],
    target_urls: [],
    completion_criteria: "Google connector installed and at least one account authenticated",
    showIf: r => r.google_gmail || r.google_calendar || r.google_drive,
  },
  // ── Microsoft 365 ─────────────────────────────────────────────────────
  {
    id: "microsoft-outlook",
    section: "microsoft",
    title: "Connect Microsoft Outlook",
    description: "Install the Outlook MCP connector so Claude can read, search, and summarize your email.",
    why: "With Outlook connected, you can ask Claude to triage your inbox, summarize threads, or draft replies — using your real email without copy-pasting.",
    click_steps: [
      "Open Claude Desktop → Settings → Connectors.",
      "Search for 'Outlook' or 'Microsoft' in the connector library.",
      "Click Install and sign in with your Microsoft account when prompted.",
      "If you have multiple accounts, add each one separately.",
    ],
    notes: ["Uses Microsoft OAuth — no admin setup needed beyond signing in."],
    links: [],
    target_urls: [],
    completion_criteria: "Outlook connector installed and Microsoft account authenticated",
    showIf: r => r.microsoft_outlook,
  },
  {
    id: "microsoft-calendar",
    section: "microsoft",
    title: "Connect Microsoft Calendar",
    description: "Add the Microsoft Calendar connector so Claude can check your schedule, find free time, and create events.",
    why: "Calendar access lets Claude answer 'what's on my schedule?' and 'find me a free hour Thursday' — without you opening the calendar app.",
    click_steps: [
      "Open Claude Desktop → Settings → Connectors.",
      "Search for 'Microsoft Calendar' or look for it alongside the Outlook connector.",
      "Click Install and authenticate with your Microsoft account.",
    ],
    notes: ["If the Outlook and Calendar connectors share the same account, you may only need to authenticate once."],
    links: [],
    target_urls: [],
    completion_criteria: "Microsoft Calendar connector installed and authenticated",
    showIf: r => r.microsoft_calendar,
  },
  // ── Developer Tools ───────────────────────────────────────────────────
  {
    id: "github",
    section: "developer",
    title: "Connect GitHub",
    description: "Install the GitHub MCP connector so Claude can browse repos, review PRs, search code, and manage issues.",
    why: "With GitHub connected, you can ask Claude to summarize a PR, find where a function is defined, or create an issue — without leaving your current context.",
    click_steps: [
      "Open Claude Desktop → Settings → Connectors.",
      "Search for 'GitHub' and click Install.",
      "Authenticate with your GitHub account when prompted.",
    ],
    notes: ["Claude gets read access to your repos by default. Write access (creating PRs, issues) requires additional OAuth scopes."],
    links: [],
    target_urls: [],
    completion_criteria: "GitHub connector installed and authenticated",
    showIf: r => r.github || r.wants_app_dev,
  },
  {
    id: "vercel-connector",
    section: "developer",
    title: "Connect Vercel",
    description: "Install the Vercel MCP connector so Claude can check deployment status, view build logs, and manage your projects.",
    why: "With Vercel connected, you can ask Claude to summarize a failed build, check which deployment is live, or review runtime logs — without leaving your editor.",
    click_steps: [
      "Open Claude Desktop → Settings → Connectors.",
      "Search for 'Vercel' and click Install.",
      "Authenticate with your Vercel account when prompted.",
    ],
    notes: [],
    links: [],
    target_urls: [],
    completion_criteria: "Vercel connector installed and authenticated",
    showIf: r => r.vercel || r.wants_app_dev,
  },
  // ── Memory ────────────────────────────────────────────────────────────
  {
    id: "supabase-project",
    section: "memory",
    title: "Create a Supabase Project",
    description: "Supabase is where Claude's persistent memory (your Personal Knowledge Base) lives. Create a free project — it takes about 2 minutes.",
    why: "Without persistent memory, Claude forgets everything between sessions. The PKB lets Claude remember decisions you've made, facts you've told it, and context about your work.",
    click_steps: [
      "Go to supabase.com and create a free account (or sign in).",
      "Click 'New project' and choose a name like 'Claude Memory'.",
      "Set a strong database password and save it somewhere safe.",
      "Wait for the project to finish provisioning (about 60 seconds).",
      "Go to Settings → API and copy the Project URL and anon key — you'll need these next.",
    ],
    notes: ["The free tier is plenty for personal use."],
    links: [{ label: "Supabase", url: "https://supabase.com" }],
    target_urls: ["supabase.com", "app.supabase.com"],
    completion_criteria: "Supabase project created; Project URL and anon key saved",
    showIf: r => r.pkb || r.supabase_db || r.wants_app_dev,
  },
  {
    id: "pkb-setup",
    section: "memory",
    title: "Set Up the Knowledge Base",
    description: "Install and configure the PKB MCP server so Claude can save and search memories across all sessions.",
    why: "The PKB turns Claude from a stateless chatbot into a system that actually knows you. It remembers your preferences, past decisions, and important context.",
    click_steps: [
      "Open Claude Desktop → Settings → Connectors.",
      "Search for 'PKB' or 'Knowledge Base' and install it.",
      "Enter your Supabase Project URL and anon key when prompted.",
      "Claude will automatically create the database table on first use.",
    ],
    notes: [
      "Once connected, tell Claude to save something: 'Remember that I prefer dark mode'. Then start a new session and ask 'What do I prefer about UI?' — it should recall it.",
    ],
    links: [],
    target_urls: [],
    completion_criteria: "PKB connector installed; Claude can save and retrieve memories",
    showIf: r => r.pkb,
  },
  {
    id: "claude-md",
    section: "memory",
    title: "Write Your CLAUDE.md",
    description: "CLAUDE.md is a file you create in your home directory that tells Claude who you are, how you want to communicate, and what tools are connected.",
    why: "Claude reads CLAUDE.md at the start of every Claude Code session. It's how Claude knows your name, your timezone, your communication preferences, and which MCP tools to use without you explaining every time.",
    click_steps: [
      "Open a terminal.",
      "Run `claude` to open Claude Code.",
      "Ask Claude to help you write a CLAUDE.md: 'Help me create a CLAUDE.md file. Ask me questions about my setup and preferences.'",
      "Claude will ask you questions and generate the file.",
    ],
    notes: [
      "You can always edit CLAUDE.md later — it's just a text file in your home directory.",
      "The more detail you put in, the better Claude will behave by default.",
    ],
    links: [],
    target_urls: [],
    completion_criteria: "CLAUDE.md created at ~/CLAUDE.md (or C:\\Users\\{name}\\CLAUDE.md on Windows)",
  },
  // ── Phone ─────────────────────────────────────────────────────────────
  {
    id: "whatsapp-bot",
    section: "phone",
    title: "Connect WhatsApp",
    description: "Set up a WhatsApp integration so you can message Claude from your phone using WhatsApp.",
    why: "With WhatsApp connected, you can send messages to Claude from anywhere and get responses with your full MCP tool stack available — calendar, email, files, and more.",
    click_steps: [
      "You'll need a Twilio account with a WhatsApp-enabled number, or a service like waha.dev.",
      "Follow the Claude Code WhatsApp setup guide to configure the webhook and connect it to your Claude instance.",
    ],
    notes: ["Your WhatsApp messages route through your local Claude — no third-party AI service sees them."],
    links: [],
    target_urls: [],
    completion_criteria: "WhatsApp connected and Claude replies to test message",
    showIf: r => r.messaging_app === "whatsapp",
  },
  {
    id: "telegram-bot",
    section: "phone",
    title: "Create a Telegram Bot",
    description: "Create a Telegram bot that connects to your Claude instance so you can message Claude from your phone.",
    why: "With Telegram connected, you can text Claude from anywhere — ask it to check your calendar, look something up, or run a task — and it'll reply with your full MCP tool stack available.",
    click_steps: [
      "Open Telegram and search for '@BotFather'.",
      "Send '/newbot' and follow the prompts to create your bot.",
      "Copy the bot token BotFather gives you.",
      "Follow the Claude Code Telegram setup guide to connect the bot to your Claude instance.",
    ],
    notes: ["Your Telegram messages go directly to your local Claude — they don't go through any third-party service."],
    links: [{ label: "Telegram BotFather", url: "https://t.me/BotFather" }],
    target_urls: ["t.me/BotFather", "telegram.org"],
    completion_criteria: "Telegram bot created and connected to Claude Code",
    showIf: r => r.messaging_app === "telegram",
  },
  // ── Automation ────────────────────────────────────────────────────────
  {
    id: "scheduled-workflows",
    section: "automation",
    title: "Set Up Scheduled Workflows",
    description: "Configure Claude to run tasks automatically on a schedule — daily digests, health checks, action item reviews.",
    why: "Scheduled workflows turn Claude from a reactive tool into a proactive assistant. Instead of asking Claude to check your email every morning, it just does it and sends you a summary.",
    click_steps: [
      "Open Claude Code and run `/schedule` to see available workflow options.",
      "Set up a daily digest: ask Claude 'Create a daily digest that checks my calendar and email each morning at 8am.'",
      "Review the scheduled task and approve it.",
    ],
    notes: [
      "Scheduled tasks run as background Claude Code sessions with your full MCP stack.",
      "You can review, modify, or delete schedules anytime with `/schedule list`.",
    ],
    links: [],
    target_urls: [],
    completion_criteria: "At least one scheduled workflow created and confirmed running",
    showIf: r => r.wants_briefings || r.wants_action_items,
  },
  // ── Creative Tools ────────────────────────────────────────────────────
  {
    id: "blender",
    section: "creative",
    title: "Connect Blender",
    description: "Add the Blender connector so Claude can interact with your 3D scenes, objects, and materials.",
    why: "With Blender connected, you can ask Claude to describe a scene, generate object placements, or help you script repetitive modeling tasks.",
    click_steps: [
      "Open Claude Desktop → Settings → Connectors.",
      "Search for 'Blender' and click Connect.",
      "Follow the authorization flow to link your Blender account.",
    ],
    notes: ["This is a cloud-based connector — no local server install required."],
    links: [],
    target_urls: [],
    completion_criteria: "Blender connector installed and authenticated",
    showIf: r => r.creative_tools.includes("blender"),
  },
  {
    id: "adobe-cc",
    section: "creative",
    title: "Connect Adobe Creative Cloud",
    description: "Add the Adobe CC connector so Claude can assist with your Creative Cloud apps and assets.",
    why: "With Adobe CC connected, Claude can interact with your creative projects — helping with scripting, asset management, and workflow automation across Photoshop, Illustrator, and other CC apps.",
    click_steps: [
      "Open Claude Desktop → Settings → Connectors.",
      "Search for 'Adobe' and click Connect.",
      "Sign in with your Adobe ID when prompted.",
    ],
    notes: ["This is a cloud-based connector — no local server install required."],
    links: [],
    target_urls: [],
    completion_criteria: "Adobe CC connector installed and authenticated",
    showIf: r => r.creative_tools.includes("adobe-cc"),
  },
  {
    id: "autodesk-fusion",
    section: "creative",
    title: "Connect Autodesk Fusion",
    description: "Add the Autodesk Fusion connector so Claude can help with your CAD designs, components, and projects.",
    why: "With Fusion connected, Claude can assist with design queries, script automation, and project navigation — saving time on repetitive CAD tasks.",
    click_steps: [
      "Open Claude Desktop → Settings → Connectors.",
      "Search for 'Autodesk Fusion' and click Connect.",
      "Authenticate with your Autodesk account when prompted.",
    ],
    notes: ["This is a cloud-based connector — no local server install required."],
    links: [],
    target_urls: [],
    completion_criteria: "Autodesk Fusion connector installed and authenticated",
    showIf: r => r.creative_tools.includes("autodesk-fusion"),
  },
  {
    id: "ableton",
    section: "creative",
    title: "Connect Ableton",
    description: "Add the Ableton connector so Claude can interact with your Live sessions, clips, and production workflow.",
    why: "With Ableton connected, Claude can help describe a set, assist with MIDI scripting, and answer questions about your session's structure.",
    click_steps: [
      "Open Claude Desktop → Settings → Connectors.",
      "Search for 'Ableton' and click Connect.",
      "Follow the authorization flow to link your Ableton account.",
    ],
    notes: ["This is a cloud-based connector — no local server install required."],
    links: [],
    target_urls: [],
    completion_criteria: "Ableton connector installed and authenticated",
    showIf: r => r.creative_tools.includes("ableton"),
  },
  {
    id: "sketchup",
    section: "creative",
    title: "Connect SketchUp",
    description: "Add the SketchUp connector so Claude can assist with your 3D models and design workflows.",
    why: "With SketchUp connected, Claude can help you navigate and describe models, generate layout ideas, and assist with repetitive design operations.",
    click_steps: [
      "Open Claude Desktop → Settings → Connectors.",
      "Search for 'SketchUp' and click Connect.",
      "Authenticate with your Trimble account when prompted.",
    ],
    notes: ["This is a cloud-based connector — no local server install required."],
    links: [],
    target_urls: [],
    completion_criteria: "SketchUp connector installed and authenticated",
    showIf: r => r.creative_tools.includes("sketchup"),
  },
  {
    id: "affinity",
    section: "creative",
    title: "Connect Affinity",
    description: "Add the Affinity connector so Claude can work alongside your Affinity Publisher, Designer, or Photo projects.",
    why: "With Affinity connected, Claude can assist with document queries, help automate repetitive tasks, and provide guidance on tools and techniques within your projects.",
    click_steps: [
      "Open Claude Desktop → Settings → Connectors.",
      "Search for 'Affinity' and click Connect.",
      "Follow the authorization flow to link your Affinity account.",
    ],
    notes: ["This is a cloud-based connector — no local server install required."],
    links: [],
    target_urls: [],
    completion_criteria: "Affinity connector installed and authenticated",
    showIf: r => r.creative_tools.includes("affinity"),
  },
  // ── Personal Finance ──────────────────────────────────────────────────
  {
    id: "monarch",
    section: "finance",
    title: "Connect Monarch Money",
    description: "Add the Monarch Money connector so Claude can query your spending, budgets, and net worth.",
    why: "With Monarch connected, you can ask Claude 'how much did I spend on dining last month?' or 'am I on track with my budget?' — using your real financial data.",
    click_steps: [
      "Open Claude Desktop → Settings → Connectors.",
      "Search for 'Monarch' and click Connect.",
      "Sign in with your Monarch Money account when prompted.",
    ],
    notes: ["Claude can read your financial data but cannot make transactions or changes."],
    links: [],
    target_urls: [],
    completion_criteria: "Monarch Money connector installed and authenticated",
    showIf: r => r.finance_tools.includes("monarch"),
  },
  {
    id: "quickbooks",
    section: "finance",
    title: "Connect QuickBooks",
    description: "Add the QuickBooks connector so Claude can access your business financial data, invoices, and accounts.",
    why: "With QuickBooks connected, you can ask Claude about outstanding invoices, cash flow, or expense categories — without exporting reports.",
    click_steps: [
      "Open Claude Desktop → Settings → Connectors.",
      "Search for 'QuickBooks' and click Connect.",
      "Sign in with your Intuit account when prompted.",
    ],
    notes: ["Claude can read your QuickBooks data but cannot modify transactions or settings."],
    links: [],
    target_urls: [],
    completion_criteria: "QuickBooks connector installed and authenticated",
    showIf: r => r.finance_tools.includes("quickbooks"),
  },
  // ── Note-taking ───────────────────────────────────────────────────────
  {
    id: "granola",
    section: "notetaking",
    title: "Connect Granola",
    description: "Add the Granola connector so Claude can access your meeting notes and transcripts.",
    why: "With Granola connected, Claude can summarize meetings, extract action items, and help you find what was said in a past meeting — without re-reading the transcript yourself.",
    click_steps: [
      "Open Claude Desktop → Settings → Connectors.",
      "Search for 'Granola' and click Connect.",
      "Sign in with your Granola account when prompted.",
    ],
    notes: [],
    links: [],
    target_urls: [],
    completion_criteria: "Granola connector installed and authenticated",
    showIf: r => r.note_taking_tool === "granola" || r.wants_note_taking_setup,
  },
  {
    id: "notion",
    section: "notetaking",
    title: "Connect Notion",
    description: "Add the Notion connector so Claude can read and write to your Notion workspace.",
    why: "With Notion connected, Claude can search your notes, summarize pages, and help you create or update content — without switching apps.",
    click_steps: [
      "Open Claude Desktop → Settings → Connectors.",
      "Search for 'Notion' and click Connect.",
      "Authorize access to your Notion workspace when prompted.",
    ],
    notes: ["You can control which pages and databases Claude can access during the authorization step."],
    links: [],
    target_urls: [],
    completion_criteria: "Notion connector installed and workspace authorized",
    showIf: r => r.note_taking_tool === "notion",
  },
  // ── Document Creation & File Organization ────────────────────────────
  {
    id: "microsoft-sharepoint",
    section: "microsoft",
    title: "Connect SharePoint / OneDrive",
    description: "Add the SharePoint connector so Claude can search, read, and navigate your organization's files and documents.",
    why: "With SharePoint connected, Claude can find files, summarize documents, and help you locate content across your organization's shared drives — without manually browsing folders.",
    click_steps: [
      "Open Claude Desktop → Settings → Connectors.",
      "Search for 'SharePoint' or 'OneDrive' and click Install.",
      "Sign in with your Microsoft account and authorize the requested permissions.",
    ],
    notes: ["Access is limited to files and sites your account can already see — Claude respects your existing SharePoint permissions."],
    links: [],
    target_urls: [],
    completion_criteria: "SharePoint connector installed and at least one site accessible",
    showIf: r => r.microsoft_sharepoint,
  },
  // ── Finish ────────────────────────────────────────────────────────────
  {
    id: "file-system-mcp",
    section: "finish",
    title: "Enable File System Access",
    description: "Configure Claude's built-in File System connector to give it access to folders on your computer.",
    why: "File system access lets Claude read documents, search files, and work with local content — without you copy-pasting file contents into the chat. It's useful across everything from code projects to document drafts.",
    click_steps: [
      "Open Claude Desktop → Settings → Connectors.",
      "Find 'File System' in the connector list (it may already be installed).",
      "Click Configure and specify which folders Claude should have access to.",
      "Start with your home directory or a dedicated 'Claude workspace' folder.",
    ],
    notes: [
      "Only grant access to folders you're comfortable with Claude reading.",
      "You can change the allowed folders at any time in Connector settings.",
    ],
    links: [],
    target_urls: [],
    completion_criteria: "File System connector configured with at least one allowed folder",
  },
  {
    id: "desktop-commander",
    section: "finish",
    title: "Install Desktop Commander MCP",
    description: "Desktop Commander gives Claude the ability to search files, manage processes, and run shell commands on your Windows machine.",
    why: "With Desktop Commander, Claude can help you with system-level tasks — searching for files across your entire drive, reading terminal output, managing running processes, and executing commands. It makes Claude significantly more useful for daily Windows work.",
    click_steps: [
      "Open Claude Desktop → Settings → Connectors.",
      "Search for 'Desktop Commander' and click Install.",
      "Review the permissions and click Approve to grant access.",
    ],
    notes: [
      "Desktop Commander runs locally on your machine — your data doesn't leave your computer.",
      "You can restrict which directories and commands it has access to in the settings.",
    ],
    links: [],
    target_urls: [],
    completion_criteria: "Desktop Commander connector installed and running",
    showIf: r => r.os === "windows",
  },
  {
    id: "connect-extension",
    section: "finish",
    title: "Connect the AI Office Extension",
    description: "Install the AI Office Chrome extension and link it to your account. The extension gives Claude live context about whatever page you're on.",
    why: "With the extension connected, Claude knows what you're looking at. You can ask 'What should I do on this page?' and get step-specific guidance — or run quick actions like Summarize or Key Facts on any page.",
    click_steps: [
      "Install the AI Office Chrome extension from the link below.",
      "Click the AI Office icon in your toolbar to open the side panel.",
      "Enter your companion server URL (default: http://127.0.0.1:7848).",
      "Paste your AI Office token from your dashboard.",
      "Click Connect — the status dot should turn green.",
    ],
    notes: ["Your companion server must be running for the extension to connect. Start it with: `python server/server.py`"],
    links: [],
    target_urls: ["aioffice.app"],
    completion_criteria: "Extension installed, companion server running, status dot green",
  },
  {
    id: "first-session",
    section: "finish",
    title: "Run Your First Full Session",
    description: "Open Claude Code and try a real task that uses your connected tools. This confirms everything is wired up correctly.",
    why: "The best way to verify your setup is to actually use it. A real task will exercise your MCP connections and show you what Claude can now do.",
    click_steps: [
      "Open a terminal and run `claude`.",
      "Try one of these: 'What's on my calendar today?' / 'Summarize my last 3 emails' / 'What did I save to memory about my preferences?'",
      "If Claude uses your MCP tools (you'll see it calling them), your setup is working.",
    ],
    notes: ["If Claude can't access a tool, check Claude Desktop → Connectors to make sure it's installed and authenticated."],
    links: [],
    target_urls: [],
    completion_criteria: "Claude successfully uses at least one connected MCP tool in a live session",
  },
];
