-- AI Office — Telemetry capture + improvement-suggestion review

-- Privacy: opt-in. Users explicitly turn telemetry on from the dashboard.
alter table profiles add column allow_telemetry boolean default false;

-- Per-question events sent from the extension after each chat turn.
-- The session_id is a rotating per-day random string set by the extension,
-- not tied to the user's account. user_id is included only because the
-- API endpoint authenticates the call via the extension token; we drop it
-- before any analysis.
create table chat_telemetry (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users on delete cascade,
  session_id text not null,
  step_id text,                 -- the active setup step at the moment of asking
  page_domain text,             -- e.g. "console.anthropic.com" — never the full URL
  scrubbed_prompt text not null,
  marked_complete_within_5min boolean default false,
  created_at timestamptz default now()
);

create index chat_telemetry_step_id_idx on chat_telemetry(step_id);
create index chat_telemetry_created_at_idx on chat_telemetry(created_at desc);

-- 90-day retention is enforced by a scheduled job (added later if desired).

-- Proposed instruction edits, generated by Claude analyzing telemetry.
-- Claude scores each suggestion by clarity-of-fix (1-5); we only persist 4-5s.
create table template_suggestions (
  id uuid primary key default gen_random_uuid(),
  step_id text not null,                   -- step template id (e.g. "claude-code-mcp")
  field text not null,                     -- "description" | "why" | "click_steps[N]" | "notes[N]"
  current_value text not null,
  proposed_value text not null,
  rationale text not null,                 -- why this edit helps
  triggering_question text not null,       -- the user prompt that surfaced the friction
  confidence int not null check (confidence between 1 and 5),
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected', 'merged', 'failed')),
  pr_url text,
  pr_number int,
  reviewed_at timestamptz,
  reviewer_notes text,
  created_at timestamptz default now()
);

create index template_suggestions_status_idx on template_suggestions(status);
create index template_suggestions_step_id_idx on template_suggestions(step_id);

-- Admin role: hardcoded for now via a flag on profiles. We'll grow into a
-- proper role table when we add a second admin.
alter table profiles add column is_admin boolean default false;

-- RLS for the new tables.
alter table chat_telemetry enable row level security;
alter table template_suggestions enable row level security;

-- Telemetry rows are write-only from the user's side (no SELECT for them).
-- Admins can read all rows.
create policy "users can insert their own telemetry"
  on chat_telemetry for insert
  with check (auth.uid() = user_id);

create policy "admins can read all telemetry"
  on chat_telemetry for select
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

-- Only admins can interact with suggestions.
create policy "admins can read suggestions"
  on template_suggestions for select
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));

create policy "admins can update suggestions"
  on template_suggestions for update
  using (exists (select 1 from profiles where id = auth.uid() and is_admin = true));
